
package geospace.control.agent.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ServiceAgentEndpointService", targetNamespace = "http://service.agent.control.geospace/", wsdlLocation = "http://localhost:10508/AgentService?wsdl")
public class ServiceAgentEndpointService
    extends Service
{

    private final static URL SERVICEAGENTENDPOINTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(geospace.control.agent.service.ServiceAgentEndpointService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = geospace.control.agent.service.ServiceAgentEndpointService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:10508/AgentService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:10508/AgentService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SERVICEAGENTENDPOINTSERVICE_WSDL_LOCATION = url;
    }

    public ServiceAgentEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceAgentEndpointService() {
        super(SERVICEAGENTENDPOINTSERVICE_WSDL_LOCATION, new QName("http://service.agent.control.geospace/", "ServiceAgentEndpointService"));
    }

    /**
     * 
     * @return
     *     returns ServiceAgentEndpoint
     */
    @WebEndpoint(name = "ServiceAgentEndpointPort")
    public ServiceAgentEndpoint getServiceAgentEndpointPort() {
        return super.getPort(new QName("http://service.agent.control.geospace/", "ServiceAgentEndpointPort"), ServiceAgentEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceAgentEndpoint
     */
    @WebEndpoint(name = "ServiceAgentEndpointPort")
    public ServiceAgentEndpoint getServiceAgentEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.agent.control.geospace/", "ServiceAgentEndpointPort"), ServiceAgentEndpoint.class, features);
    }

}
