
package geospace.control.agent.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ServiceAgentEndpoint", targetNamespace = "http://service.agent.control.geospace/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceAgentEndpoint {


    /**
     * 
     * @param authToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "agentId", targetNamespace = "")
    @RequestWrapper(localName = "getAgentId", targetNamespace = "http://service.agent.control.geospace/", className = "geospace.control.agent.service.GetAgentId")
    @ResponseWrapper(localName = "getAgentIdResponse", targetNamespace = "http://service.agent.control.geospace/", className = "geospace.control.agent.service.GetAgentIdResponse")
    public String getAgentId(
        @WebParam(name = "authToken", targetNamespace = "")
        String authToken);

    /**
     * 
     * @param controllerState
     * @param authToken
     */
    @WebMethod
    @RequestWrapper(localName = "setControllerState", targetNamespace = "http://service.agent.control.geospace/", className = "geospace.control.agent.service.SetControllerState")
    @ResponseWrapper(localName = "setControllerStateResponse", targetNamespace = "http://service.agent.control.geospace/", className = "geospace.control.agent.service.SetControllerStateResponse")
    public void setControllerState(
        @WebParam(name = "authToken", targetNamespace = "")
        String authToken,
        @WebParam(name = "controllerState", targetNamespace = "")
        ControllerState controllerState);

    /**
     * 
     * @param authToken
     * @return
     *     returns geospace.control.agent.service.CurrentGameState
     */
    @WebMethod
    @WebResult(name = "lastGameState", targetNamespace = "")
    @RequestWrapper(localName = "getLastGameState", targetNamespace = "http://service.agent.control.geospace/", className = "geospace.control.agent.service.GetLastGameState")
    @ResponseWrapper(localName = "getLastGameStateResponse", targetNamespace = "http://service.agent.control.geospace/", className = "geospace.control.agent.service.GetLastGameStateResponse")
    public CurrentGameState getLastGameState(
        @WebParam(name = "authToken", targetNamespace = "")
        String authToken);

    /**
     * 
     * @param agentName
     * @param agentDescription
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "authToken", targetNamespace = "")
    @RequestWrapper(localName = "connectAgent", targetNamespace = "http://service.agent.control.geospace/", className = "geospace.control.agent.service.ConnectAgent")
    @ResponseWrapper(localName = "connectAgentResponse", targetNamespace = "http://service.agent.control.geospace/", className = "geospace.control.agent.service.ConnectAgentResponse")
    public String connectAgent(
        @WebParam(name = "agentName", targetNamespace = "")
        String agentName,
        @WebParam(name = "agentDescription", targetNamespace = "")
        String agentDescription);

}
